version: '3.8'
services:
  postgres_database:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST_DOCKER}
    ports:
      - '1234:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - backend

  backend:
    container_name: backend_container
    build: ./backend/
    environment:
      - DB_HOST=postgres_database
    restart: 'unless-stopped'
    ports:
      - "8080:8080"
    depends_on:
      - postgres_database
    volumes:
      - ./backend/.env:/app/.env
    networks:
      - backend
      - frontend

  frontend:
    container_name: frontend_container
    build: ./frontend/
    restart: 'unless-stopped'
    ports:
      - '80:3000'
    depends_on:
      - backend
    networks:
      - frontend

volumes:
  pg_data:

networks:
  backend:
  frontend: