// Code generated by MockGen. DO NOT EDIT.
// Source: .\backend\internal\db\database.go

// Package mockData is a generated GoMock package.
package mock

import (
	models "adsb-api/internal/global/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDatabase is a mockData of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
}

// MockDatabaseMockRecorder is the mockData recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mockData instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockDatabase) Begin() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin")
	ret0, _ := ret[0].(error)
	return ret0
}

// Begin indicates an expected call of Begin.
func (mr *MockDatabaseMockRecorder) Begin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockDatabase)(nil).Begin))
}

// BulkInsertAircraftCurrent mocks base method.
func (m *MockDatabase) BulkInsertAircraftCurrent(aircraft []models.AircraftCurrentModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsertAircraftCurrent", aircraft)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkInsertAircraftCurrent indicates an expected call of BulkInsertAircraftCurrent.
func (mr *MockDatabaseMockRecorder) BulkInsertAircraftCurrent(aircraft interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsertAircraftCurrent", reflect.TypeOf((*MockDatabase)(nil).BulkInsertAircraftCurrent), aircraft)
}

// Close mocks base method.
func (m *MockDatabase) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDatabaseMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDatabase)(nil).Close))
}

// Commit mocks base method.
func (m *MockDatabase) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockDatabaseMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockDatabase)(nil).Commit))
}

// CreateAircraftCurrentTable mocks base method.
func (m *MockDatabase) CreateAircraftCurrentTable() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAircraftCurrentTable")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAircraftCurrentTable indicates an expected call of CreateAircraftCurrentTable.
func (mr *MockDatabaseMockRecorder) CreateAircraftCurrentTable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAircraftCurrentTable", reflect.TypeOf((*MockDatabase)(nil).CreateAircraftCurrentTable))
}

// CreateAircraftHistoryTable mocks base method.
func (m *MockDatabase) CreateAircraftHistoryTable() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAircraftHistoryTable")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAircraftHistoryTable indicates an expected call of CreateAircraftHistoryTable.
func (mr *MockDatabaseMockRecorder) CreateAircraftHistoryTable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAircraftHistoryTable", reflect.TypeOf((*MockDatabase)(nil).CreateAircraftHistoryTable))
}

// CreateAircraftHistoryTimestampIndex mocks base method.
func (m *MockDatabase) CreateAircraftHistoryTimestampIndex() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAircraftHistoryTimestampIndex")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAircraftHistoryTimestampIndex indicates an expected call of CreateAircraftHistoryTimestampIndex.
func (mr *MockDatabaseMockRecorder) CreateAircraftHistoryTimestampIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAircraftHistoryTimestampIndex", reflect.TypeOf((*MockDatabase)(nil).CreateAircraftHistoryTimestampIndex))
}

// DeleteOldHistory mocks base method.
func (m *MockDatabase) DeleteOldHistory(time int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldHistory", time)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOldHistory indicates an expected call of DeleteOldHistory.
func (mr *MockDatabaseMockRecorder) DeleteOldHistory(time interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOldHistory", reflect.TypeOf((*MockDatabase)(nil).DeleteOldHistory), time)
}

// DropAircraftCurrentTable mocks base method.
func (m *MockDatabase) DropAircraftCurrentTable() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropAircraftCurrentTable")
	ret0, _ := ret[0].(error)
	return ret0
}

// DropAircraftCurrentTable indicates an expected call of DropAircraftCurrentTable.
func (mr *MockDatabaseMockRecorder) DropAircraftCurrentTable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropAircraftCurrentTable", reflect.TypeOf((*MockDatabase)(nil).DropAircraftCurrentTable))
}

// InsertHistoryFromCurrent mocks base method.
func (m *MockDatabase) InsertHistoryFromCurrent() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertHistoryFromCurrent")
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertHistoryFromCurrent indicates an expected call of InsertHistoryFromCurrent.
func (mr *MockDatabaseMockRecorder) InsertHistoryFromCurrent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertHistoryFromCurrent", reflect.TypeOf((*MockDatabase)(nil).InsertHistoryFromCurrent))
}

// Rollback mocks base method.
func (m *MockDatabase) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockDatabaseMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockDatabase)(nil).Rollback))
}

// SelectAllColumnHistoryByIcao mocks base method.
func (m *MockDatabase) SelectAllColumnHistoryByIcao(search string) ([]models.AircraftHistoryModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAllColumnHistoryByIcao", search)
	ret0, _ := ret[0].([]models.AircraftHistoryModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAllColumnHistoryByIcao indicates an expected call of SelectAllColumnHistoryByIcao.
func (mr *MockDatabaseMockRecorder) SelectAllColumnHistoryByIcao(search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAllColumnHistoryByIcao", reflect.TypeOf((*MockDatabase)(nil).SelectAllColumnHistoryByIcao), search)
}

// SelectAllColumnHistoryByIcaoFilterByTimestamp mocks base method.
func (m *MockDatabase) SelectAllColumnHistoryByIcaoFilterByTimestamp(search string, hour int) ([]models.AircraftHistoryModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAllColumnHistoryByIcaoFilterByTimestamp", search, hour)
	ret0, _ := ret[0].([]models.AircraftHistoryModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAllColumnHistoryByIcaoFilterByTimestamp indicates an expected call of SelectAllColumnHistoryByIcaoFilterByTimestamp.
func (mr *MockDatabaseMockRecorder) SelectAllColumnHistoryByIcaoFilterByTimestamp(search, hour interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAllColumnHistoryByIcaoFilterByTimestamp", reflect.TypeOf((*MockDatabase)(nil).SelectAllColumnHistoryByIcaoFilterByTimestamp), search, hour)
}

// SelectAllColumnsAircraftCurrent mocks base method.
func (m *MockDatabase) SelectAllColumnsAircraftCurrent() ([]models.AircraftCurrentModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAllColumnsAircraftCurrent")
	ret0, _ := ret[0].([]models.AircraftCurrentModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAllColumnsAircraftCurrent indicates an expected call of SelectAllColumnsAircraftCurrent.
func (mr *MockDatabaseMockRecorder) SelectAllColumnsAircraftCurrent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAllColumnsAircraftCurrent", reflect.TypeOf((*MockDatabase)(nil).SelectAllColumnsAircraftCurrent))
}
