// Code generated by MockGen. DO NOT EDIT.
// Source: .\backend\internal\db\database.go

// Package db is a generated GoMock package.
package db

import (
	"adsb-api/internal/global/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDatabase is a mock of PgDatabase interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// BulkInsertAircraftCurrent mocks base method.
func (m *MockDatabase) BulkInsertAircraftCurrent(aircraft []models.AircraftCurrentModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsertAircraftCurrent", aircraft)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkInsertAircraftCurrent indicates an expected call of BulkInsertAircraftCurrent.
func (mr *MockDatabaseMockRecorder) BulkInsertAircraftCurrent(aircraft interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsertAircraftCurrent", reflect.TypeOf((*MockDatabase)(nil).BulkInsertAircraftCurrent), aircraft)
}

// Close mocks base method.
func (m *MockDatabase) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDatabaseMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDatabase)(nil).Close))
}

// CreateAdsbTables mocks base method.
func (m *MockDatabase) CreateAdsbTables() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdsbTables")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAdsbTables indicates an expected call of CreateAdsbTables.
func (mr *MockDatabaseMockRecorder) CreateAdsbTables() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdsbTables", reflect.TypeOf((*MockDatabase)(nil).CreateAdsbTables))
}

// DeleteOldCurrent mocks base method.
func (m *MockDatabase) DeleteOldCurrent() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldCurrent")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOldCurrent indicates an expected call of DeleteOldCurrent.
func (mr *MockDatabaseMockRecorder) DeleteOldCurrent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOldCurrent", reflect.TypeOf((*MockDatabase)(nil).DeleteOldCurrent))
}

// GetCurrentAircraft mocks base method.
func (m *MockDatabase) GetCurrentAircraft() ([]models.AircraftCurrentModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentAircraft")
	ret0, _ := ret[0].([]models.AircraftCurrentModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentAircraft indicates an expected call of GetCurrentAircraft.
func (mr *MockDatabaseMockRecorder) GetCurrentAircraft() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentAircraft", reflect.TypeOf((*MockDatabase)(nil).GetCurrentAircraft))
}

// GetHistoryByIcao mocks base method.
func (m *MockDatabase) GetHistoryByIcao(search string) ([]models.AircraftHistoryModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistoryByIcao", search)
	ret0, _ := ret[0].([]models.AircraftHistoryModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistoryByIcao indicates an expected call of GetHistoryByIcao.
func (mr *MockDatabaseMockRecorder) GetHistoryByIcao(search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistoryByIcao", reflect.TypeOf((*MockDatabase)(nil).GetHistoryByIcao), search)
}

// InsertHistoryFromCurrent mocks base method.
func (m *MockDatabase) InsertHistoryFromCurrent() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertHistoryFromCurrent")
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertHistoryFromCurrent indicates an expected call of InsertHistoryFromCurrent.
func (mr *MockDatabaseMockRecorder) InsertHistoryFromCurrent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertHistoryFromCurrent", reflect.TypeOf((*MockDatabase)(nil).InsertHistoryFromCurrent))
}
